version: '3.3'

services:
  ubuntu:
    image: ubuntu
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://10.66.6.18:12201"
        tag: "alpine"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: "America/Boise"
    networks:
      - docker-network
networks:
  docker-network:

